### PR TITLE
..

### PR DESCRIPTION
**Pull request by golisopod531**
....

### CODE REVIEW

**Comment by golisopod531** [comment]
Done

**Comment by KartikeSingh** [comment]
Hey @golisopod531,
I think you did something wrong, you exposed your tokens, mongodb uri to the whole world publicly.
I think you should delete that repo/ make it private.

**Comment by KartikeSingh** [comment]
Or you can just revoke your current credentials

**Comment by golisopod531** [comment]
Thx btw
Ur code works properly but the problem is that i cant get my bot to come
online so can you make a bot for me and put your code in that?

**Comment by KartikeSingh** [comment]
whats the error? maybe try following the youtube series, it might help

**Comment by golisopod531** [comment]
I saw ur series man its just i cant get it to work please can u do it for
me please

**Comment by KartikeSingh** [comment]
really sorry nowadays, I am dealing with exams

**Comment by golisopod531** [comment]
Ok can u tell me how did u host the bot?

**Comment by KartikeSingh** [comment]
Yeah, I use glitch.com for hostng

**Comment by golisopod531** [comment]
Is it free?

**Comment by KartikeSingh** [comment]
yes

**Comment by UnschooledGamer** [comment]
> yes

Are you serious? You use glitch for discord bot hosting

**Pull request closed without merging**
